// Shared logo/gradient utilities for institution components

export const DOMAIN_MAP: Record<string, string> = {
  北京大学: "pku.edu.cn",
  清华大学: "tsinghua.edu.cn",
  复旦大学: "fudan.edu.cn",
  浙江大学: "zju.edu.cn",
  上海交通大学: "sjtu.edu.cn",
  南京大学: "nju.edu.cn",
  武汉大学: "whu.edu.cn",
  中山大学: "sysu.edu.cn",
  哈尔滨工业大学: "hit.edu.cn",
  北京航空航天大学: "buaa.edu.cn",
  北京理工大学: "bit.edu.cn",
  华中科技大学: "hust.edu.cn",
  西安交通大学: "xjtu.edu.cn",
  同济大学: "tongji.edu.cn",
  中国科学院大学: "ucas.ac.cn",
  中国人民大学: "ruc.edu.cn",
  北京师范大学: "bnu.edu.cn",
  厦门大学: "xmu.edu.cn",
  四川大学: "scu.edu.cn",
  吉林大学: "jlu.edu.cn",
  大连理工大学: "dlut.edu.cn",
  东北大学: "neu.edu.cn",
  南开大学: "nankai.edu.cn",
  天津大学: "tju.edu.cn",
  重庆大学: "cqu.edu.cn",
  中南大学: "csu.edu.cn",
  华南理工大学: "scut.edu.cn",
  电子科技大学: "uestc.edu.cn",
  兰州大学: "lzu.edu.cn",
  中国农业大学: "cau.edu.cn",
  中国海洋大学: "ouc.edu.cn",
  北京邮电大学: "bupt.edu.cn",
  华东师范大学: "ecnu.edu.cn",
  中国科学技术大学: "ustc.edu.cn",
  东南大学: "seu.edu.cn",
  山东大学: "sdu.edu.cn",
  湖南大学: "hnu.edu.cn",
  西北工业大学: "nwpu.edu.cn",
  中央民族大学: "muc.edu.cn",
  西北农林科技大学: "nwafu.edu.cn",
  北京交通大学: "bjtu.edu.cn",
  北京科技大学: "ustb.edu.cn",
  北京化工大学: "buct.edu.cn",
  北京林业大学: "bjfu.edu.cn",
  中央财经大学: "cufe.edu.cn",
  对外经济贸易大学: "uibe.edu.cn",
  北京外国语大学: "bfsu.edu.cn",
  北京语言大学: "blcu.edu.cn",
  首都师范大学: "cnu.edu.cn",
  首都医科大学: "ccmu.edu.cn",
  北京中关村学院: "bjzgc.edu.cn",
  北京工业大学: "bjut.edu.cn",
  中国政法大学: "cupl.edu.cn",
  北京协和医学院: "pumc.edu.cn",
  北京中医药大学: "bucm.edu.cn",
  中央音乐学院: "ccom.edu.cn",
  中国传媒大学: "cuc.edu.cn",
  北京体育大学: "bsu.edu.cn",
  中国矿业大学: "cumt.edu.cn",
  中国石油大学: "cup.edu.cn",
  华北电力大学: "ncepu.edu.cn",
  上海大学: "shu.edu.cn",
  华东理工大学: "ecust.edu.cn",
  东华大学: "dhu.edu.cn",
  上海财经大学: "sufe.edu.cn",
  上海外国语大学: "shisu.edu.cn",
  上海音乐学院: "shcmusic.edu.cn",
  南京理工大学: "njust.edu.cn",
  南京航空航天大学: "nuaa.edu.cn",
  河海大学: "hhu.edu.cn",
  苏州大学: "suda.edu.cn",
  南京农业大学: "njau.edu.cn",
  南京医科大学: "njmu.edu.cn",
  中国药科大学: "cpu.edu.cn",
  西安电子科技大学: "xidian.edu.cn",
  长安大学: "chd.edu.cn",
  西北大学: "nwu.edu.cn",
  陕西师范大学: "snnu.edu.cn",
  浙江工业大学: "zjut.edu.cn",
  宁波大学: "nbu.edu.cn",
  中国美术学院: "caa.edu.cn",
  深圳大学: "szu.edu.cn",
  华南师范大学: "scnu.edu.cn",
  暨南大学: "jnu.edu.cn",
  南方科技大学: "sustech.edu.cn",
  哈尔滨工程大学: "hrbeu.edu.cn",
  东北林业大学: "nefu.edu.cn",
  东北农业大学: "neau.edu.cn",
  湖南师范大学: "hunnu.edu.cn",
  中南财经政法大学: "zuel.edu.cn",
  华中师范大学: "ccnu.edu.cn",
  华中农业大学: "hzau.edu.cn",
  武汉理工大学: "whut.edu.cn",
  云南大学: "ynu.edu.cn",
  贵州大学: "gzu.edu.cn",
  四川农业大学: "sicau.edu.cn",
  西南交通大学: "swjtu.edu.cn",
  西南大学: "swu.edu.cn",
  电子科技大学成都: "uestc.edu.cn",
  郑州大学: "zzu.edu.cn",
  河南大学: "henu.edu.cn",
  合肥工业大学: "hfut.edu.cn",
  安徽大学: "ahu.edu.cn",
  福州大学: "fzu.edu.cn",
  江南大学: "jiangnan.edu.cn",
  南昌大学: "ncu.edu.cn",
  广西大学: "gxu.edu.cn",
  海南大学: "hainanu.edu.cn",
  石河子大学: "shzu.edu.cn",
  新疆大学: "xju.edu.cn",
  青海大学: "qhu.edu.cn",
  西藏大学: "utibet.edu.cn",
  内蒙古大学: "imu.edu.cn",
  宁夏大学: "nxu.edu.cn",
};

export const SVG_LOGO_MAP: Record<string, string> = {
  // 仅包含已验证可用的 Wikimedia Commons SVG
  清华大学:
    "https://upload.wikimedia.org/wikipedia/commons/e/ec/Tsinghua_University_Logo.svg",
  // 其他大学使用 Google Favicon API 或 fallback
};

export function getLogoSrc(name: string): string | null {
  if (SVG_LOGO_MAP[name]) return SVG_LOGO_MAP[name];
  const domain = DOMAIN_MAP[name];
  if (domain)
    return `https://www.google.com/s2/favicons?domain=${domain}&sz=128`;
  return null;
}

export const MONOGRAM_GRADIENTS = [
  "from-blue-600 to-indigo-700",
  "from-violet-600 to-purple-700",
  "from-emerald-600 to-teal-700",
  "from-rose-600 to-pink-700",
  "from-amber-500 to-orange-600",
  "from-teal-600 to-cyan-700",
  "from-indigo-600 to-blue-700",
  "from-pink-600 to-rose-700",
] as const;

export function getGradient(id: string): string {
  let h = 0;
  for (const c of id) h = (h * 31 + c.charCodeAt(0)) >>> 0;
  return MONOGRAM_GRADIENTS[h % MONOGRAM_GRADIENTS.length];
}
